application: qrcopypaste
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: index.php

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /css
  static_dir: css